import { TriadQuality } from './triad';

/**
 * The interval role a string plays within a triad shape.
 * Displayed as a label inside the dot on the chord diagram.
 */
export type NoteRole = 'R' | 'M3' | 'm3' | 'P5' | 'd5' | 'A5';

export const NOTE_ROLE_LABEL: Record<NoteRole, string> = {
  R:  'R',
  M3: '3',
  m3: '♭3',
  P5: '5',
  d5: '♭5',
  A5: '♯5',
};

/**
 * A moveable triad voicing on 3 adjacent strings.
 *
 * Array index convention throughout: [0] = lowest-pitched string of the set,
 * [1] = middle string, [2] = highest-pitched string.
 *
 * `offsets` are relative fret positions from the base fret (the lowest fret used in
 * the shape, which is always 0 for at least one string).  Because the shape is
 * moveable, you slide the whole thing to any base fret — the offsets stay the same.
 */
export interface TriadShape {
  /** Fret offsets from base fret: [low string, mid string, high string] */
  offsets: [number, number, number];
  /** Interval role for each string: [low string, mid string, high string] */
  roles: [NoteRole, NoteRole, NoteRole];
  /** Human-readable inversion label shown below the diagram */
  label: string;
}

/**
 * Identifies a set of 3 adjacent strings a triad can be voiced on, named by
 * their standard string numbers (1 = high e ... 6 = low E).
 */
export type TriadStringSetId = 'strings123' | 'strings234' | 'strings345' | 'strings456';

export interface TriadStringSet {
  id: TriadStringSetId;
  /** String names, low to high pitch — matches TriadShape.offsets/roles order */
  strings: [string, string, string];
  /** Display label, e.g. "G · B · e" */
  label: string;
}

export const TRIAD_STRING_SETS: TriadStringSet[] = [
  { id: 'strings123', strings: ['G', 'B', 'e'], label: 'G · B · e' },
  { id: 'strings234', strings: ['D', 'G', 'B'], label: 'D · G · B' },
  { id: 'strings345', strings: ['A', 'D', 'G'], label: 'A · D · G' },
  { id: 'strings456', strings: ['E', 'A', 'D'], label: 'E · A · D' },
];

/**
 * All three closed-position voicings for each quality, for each adjacent 3-string set.
 *
 * Offsets are derived from standard-tuning open-string pitch classes
 * (E=4, A=9, D=2, G=7, B=11, e=4) via mod-12 interval arithmetic: for each string,
 * solve for the fret where (openPitchClass + fret) mod 12 equals the target role's
 * pitch class relative to an arbitrary root, adjusting octaves between adjacent
 * strings to keep the voicing closed (each string within a fourth or so of its
 * neighbor), then normalizing so the lowest fret used is 0.
 *
 * strings123 (G·B·e) is the original hand-verified table — reproduced here unchanged.
 * Verified against standard tuning (open strings: G=7, B=11, e=4 in pitch-class):
 *
 * MAJOR  root-pos  G=R(+2)  B=3(+2)  e=5(0)   e.g. C: frets 5,5,3
 *        1st-inv   G=3(+1)  B=5(0)   e=R(0)   e.g. C: frets 9,8,8
 *        2nd-inv   G=5(0)   B=R(+1)  e=3(0)   e.g. C: frets 0,1,0 (open pos)
 *
 * MINOR  root-pos  G=R(+2)  B=♭3(+1) e=5(0)   e.g. C: frets 5,4,3
 *        1st-inv   G=♭3(0)  B=5(0)   e=R(0)   e.g. C: frets 8,8,8 (barre)
 *        2nd-inv   G=5(+1)  B=R(+2)  e=♭3(0)  e.g. F: frets 5,6,4
 *
 * DIM    root-pos  G=R(+3)  B=♭3(+2) e=♭5(0)  e.g. C: frets 5,4,2
 *        1st-inv   G=♭3(+1) B=♭5(0)  e=R(+1)  e.g. C: frets 8,7,8
 *        2nd-inv   G=♭5(0)  B=R(+2)  e=♭3(0)  e.g. C: frets 11,13,11
 *
 * AUG    all inv.  G(+1)    B(+1)    e(0)     e.g. C: frets 5,5,4
 *        (augmented triad is symmetric — all 3 voicings share the same dot pattern)
 *
 * The three other string sets are generated by the same derivation (see
 * `__tests__/domain/triadShapes.test.ts` for the mod-12 verification of every shape).
 * strings345 and strings456 share identical offsets/roles because both string pairs
 * are tuned a perfect fourth apart (A–D–G and E–A–D have the same interval gaps);
 * only the string names on the diagram differ.
 */
export const TRIAD_SHAPES: Record<TriadStringSetId, Record<TriadQuality, TriadShape[]>> = {
  strings123: {
    major: [
      { offsets: [2, 2, 0], roles: ['R',  'M3', 'P5'], label: 'Root pos.' },
      { offsets: [1, 0, 0], roles: ['M3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [0, 1, 0], roles: ['P5', 'R',  'M3'], label: '2nd inv.'  },
    ],
    minor: [
      { offsets: [2, 1, 0], roles: ['R',  'm3', 'P5'], label: 'Root pos.' },
      { offsets: [0, 0, 0], roles: ['m3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 2, 0], roles: ['P5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    diminished: [
      { offsets: [3, 2, 0], roles: ['R',  'm3', 'd5'], label: 'Root pos.' },
      { offsets: [1, 0, 1], roles: ['m3', 'd5', 'R' ], label: '1st inv.'  },
      { offsets: [0, 2, 0], roles: ['d5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    augmented: [
      { offsets: [1, 1, 0], roles: ['R',  'M3', 'A5'], label: 'Root pos.' },
      { offsets: [1, 1, 0], roles: ['M3', 'A5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 1, 0], roles: ['A5', 'R',  'M3'], label: '2nd inv.'  },
    ],
  },
  strings234: {
    major: [
      { offsets: [2, 1, 0], roles: ['R',  'M3', 'P5'], label: 'Root pos.' },
      { offsets: [2, 0, 1], roles: ['M3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [0, 0, 0], roles: ['P5', 'R',  'M3'], label: '2nd inv.'  },
    ],
    minor: [
      { offsets: [2, 0, 0], roles: ['R',  'm3', 'P5'], label: 'Root pos.' },
      { offsets: [1, 0, 1], roles: ['m3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 1, 0], roles: ['P5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    diminished: [
      { offsets: [3, 1, 0], roles: ['R',  'm3', 'd5'], label: 'Root pos.' },
      { offsets: [2, 0, 2], roles: ['m3', 'd5', 'R' ], label: '1st inv.'  },
      { offsets: [0, 1, 0], roles: ['d5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    augmented: [
      { offsets: [1, 0, 0], roles: ['R',  'M3', 'A5'], label: 'Root pos.' },
      { offsets: [1, 0, 0], roles: ['M3', 'A5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 0, 0], roles: ['A5', 'R',  'M3'], label: '2nd inv.'  },
    ],
  },
  strings345: {
    major: [
      { offsets: [3, 2, 0], roles: ['R',  'M3', 'P5'], label: 'Root pos.' },
      { offsets: [2, 0, 0], roles: ['M3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 1, 0], roles: ['P5', 'R',  'M3'], label: '2nd inv.'  },
    ],
    minor: [
      { offsets: [3, 1, 0], roles: ['R',  'm3', 'P5'], label: 'Root pos.' },
      { offsets: [1, 0, 0], roles: ['m3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [2, 2, 0], roles: ['P5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    diminished: [
      { offsets: [4, 2, 0], roles: ['R',  'm3', 'd5'], label: 'Root pos.' },
      { offsets: [2, 0, 1], roles: ['m3', 'd5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 2, 0], roles: ['d5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    augmented: [
      { offsets: [2, 1, 0], roles: ['R',  'M3', 'A5'], label: 'Root pos.' },
      { offsets: [2, 1, 0], roles: ['M3', 'A5', 'R' ], label: '1st inv.'  },
      { offsets: [2, 1, 0], roles: ['A5', 'R',  'M3'], label: '2nd inv.'  },
    ],
  },
  strings456: {
    major: [
      { offsets: [3, 2, 0], roles: ['R',  'M3', 'P5'], label: 'Root pos.' },
      { offsets: [2, 0, 0], roles: ['M3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 1, 0], roles: ['P5', 'R',  'M3'], label: '2nd inv.'  },
    ],
    minor: [
      { offsets: [3, 1, 0], roles: ['R',  'm3', 'P5'], label: 'Root pos.' },
      { offsets: [1, 0, 0], roles: ['m3', 'P5', 'R' ], label: '1st inv.'  },
      { offsets: [2, 2, 0], roles: ['P5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    diminished: [
      { offsets: [4, 2, 0], roles: ['R',  'm3', 'd5'], label: 'Root pos.' },
      { offsets: [2, 0, 1], roles: ['m3', 'd5', 'R' ], label: '1st inv.'  },
      { offsets: [1, 2, 0], roles: ['d5', 'R',  'm3'], label: '2nd inv.'  },
    ],
    augmented: [
      { offsets: [2, 1, 0], roles: ['R',  'M3', 'A5'], label: 'Root pos.' },
      { offsets: [2, 1, 0], roles: ['M3', 'A5', 'R' ], label: '1st inv.'  },
      { offsets: [2, 1, 0], roles: ['A5', 'R',  'M3'], label: '2nd inv.'  },
    ],
  },
};
